name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.3, 7.4, 8.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Memcached Service
        uses: niden/actions-memcached@v7
      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
      - name: Install Composer packages
        run: |
          composer require -n --ignore-platform-reqs "phwoolcon/ci-pecl-cacher" "phpunit/phpunit:^9" "php-coveralls/php-coveralls"
          composer install -n --ignore-platform-reqs --no-suggest
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
