name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ 7.3, 7.4, 8.0 ]

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    env:
      extensions: apcu, pcov, mbstring, ctype, curl, gd, memcached
      ini: apc.enabled=1, apc.enable_cli=1, pcov.directory=.
      key: cache-v1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Before Script
        run: |
          mkdir -p build/logs
          mkdir -p coverage
          touch coverage/lcov.info
          chmod 777 coverage/lcov.info
          ls -al
          sudo apt-get install -y locales-all

      - name: Install Memcached
        uses: niden/actions-memcached@v7

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: ${{ env.ini }}
          coverage: pcov

      - name: Install composer packages
        run: |
          composer validate
          composer require -n --ignore-platform-reqs "phwoolcon/ci-pecl-cacher" "phpunit/phpunit:^9" "php-coveralls/php-coveralls"
          composer install -n --ignore-platform-reqs --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
